# Generated by Django 3.2.8 on 2021-11-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyappone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTestOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
